#pragma config(Hubs,  S1, HTServo,  HTMotor,  HTMotor,  HTMotor)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C2_1,     picollo,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     picollo1,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     lift,          tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C3_2,     picollo2,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_1,     left,          tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C4_2,     right,         tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C1_1,    picollo456,           tServoStandard)
#pragma config(Servo,  srvo_S1_C1_2,    picollo8,             tServoStandard)
#pragma config(Servo,  srvo_S1_C1_3,    grabber,              tServoStandard)
#pragma config(Servo,  srvo_S1_C1_4,    door,                 tServoStandard)
#pragma config(Servo,  srvo_S1_C1_5,    picollo5,             tServoStandard)
#pragma config(Servo,  srvo_S1_C1_6,    picollo6,             tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "library.c"

float currentHeight()
{
	return encodersToTurns(nMotorEncoder[lift]) * spoolCircumference;
}

void liftHeight(int height)
{
	int goingUp = height > currentHeight() ? 1 : -1;
	setLift(liftAutoSpeed * goingUp);
	// The goingUp variable makes it so that if it's 60->10, it waits until -10 < -60
	while (currentHeight() * goingUp < height * goingUp)
	{
		// Wait
	}
	setLift(0);
}

task main()
{

	const int maxSpeed = 100;

	zeroEncoders();

	waitForStart();

	motor[left] = maxSpeed;
	motor[right] = maxSpeed;

	wait1Msec(3610);

	motor[left] = 0;
	motor[right] = 0;

	liftHeight(60 + amountAboveTubes);
	servo[door] = 255;
	wait1Msec(3000); // TODO: Correct
	liftHeight(zeroLift);
	servo[door] = 100;
	wait1Msec(500);

}
