#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     irSeeker,       sensorI2CCustom)
#pragma config(Motor,  mtr_S1_C1_1,     picollo,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     scoop,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     liftRight,     tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     liftLeft,      tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C3_1,     right,         tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C3_2,     left,          tmotorTetrix, openLoop, encoder)
#pragma config(Servo,  srvo_S1_C4_1,    door,                 tServoStandard)
#pragma config(Servo,  srvo_S1_C4_2,    picollo2,             tServoNone)
#pragma config(Servo,  srvo_S1_C4_3,    picollo3,             tServoNone)
#pragma config(Servo,  srvo_S1_C4_4,    picollo4,             tServoNone)
#pragma config(Servo,  srvo_S1_C4_5,    picollo5,             tServoNone)
#pragma config(Servo,  srvo_S1_C4_6,    picollo6,             tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "library.c"
#include "drivers/hitechnic-irseeker-v2.h"

// Global variables
int ir[6];

// Check whether we arrived at the IR beacon
bool hasArrived(void)
{
	const int arrivedThreshold = 25; // The value the IR beacon gets when we arrive TODO: Make less arbitrary.
	for (int i = 1; i <= 5; i++)
	{
		if (ir[i] > arrivedThreshold) return true;
	}
	return false;
}

void liftHeight(int height, int speed = liftAutoSpeed)
{
	while (abs(encodersToTurns(nMotorEncoder[liftLeft]) * spoolCircumference) < height)
	{
		int goingDown = height > 0 ? 1 : -1;
		setLift(speed * goingDown);
	}
	setLift(0);
}

task main()
{

	// Go somewhat slowly so we can pick up IR
	const int maxSpeed = 100;

	// When we get no signal, we go forward for a little while; this keeps track of piccollos.
	bool wentForwardAlready = false;

	zeroEncoders();

	waitForStart();

	// Make sure we pick of the IR so go forward mann
	motor[left] = maxSpeed;
	motor[right] = maxSpeed;
	wait1Msec(3000); // TODO: Correct # for 200000 points
	motor[left] = 0;
	motor[right] = 0;

	while(true)
	{

		if (!hasArrived())
		{

			HTIRS2readAllACStrength(irSeeker, ir[1], ir[2], ir[3], ir[4], ir[5]);

			int direction = HTIRS2readACDir(irSeeker);

			const int zeroContinueTime = 200;
			const int correctDirTime = 1500;

			if (direction == 0)
			{
				if (!wentForwardAlready)
				{
					motor[left] = maxSpeed;
					motor[right] = maxSpeed;
					wait1Msec(zeroContinueTime);
					wentForwardAlready = true;
				}
				else
				{
					motor[left] = maxSpeed;
					motor[right] = -maxSpeed;
				}
			}
			else
			{
				wentForwardAlready = false;

				const float spinDivisor = 0.2;
				if (direction < 5)
				{
					motor[left] = maxSpeed * spinDivisor;
					motor[right] = maxSpeed;
				}
				else if (direction > 5)
				{
					motor[left] = maxSpeed;
					motor[right] = maxSpeed * spinDivisor;
				}
				else if (direction == 5)
				{
					motor[left] = maxSpeed;
					motor[right] = maxSpeed;
					clearTimer(T1);
					while (!hasArrived() && time1[T1] < correctDirTime)	{}
				}
			}

		}

		if (hasArrived())
		{

			motor[left] = 0;
			motor[right] = 0;
			const int height = 120 + amountAboveTubes; // So that we have room for dumping BALLS
			liftHeight(height);
			servo[door] = 0;
			break;

		}

	}

}
