#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     picollo,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     scoop,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     liftRight,     tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     liftLeft,      tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C3_1,     right,         tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C3_2,     left,          tmotorTetrix, openLoop, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "library.c"

#define driver1LeftStickX joystick.joy1_x1
#define driver1LeftStickY joystick.joy1_y1
#define driver1RightStickX joystick.joy1_x2
#define driver1RightStickY joystick.joy1_y2

#define driver2LeftStickX joystick.joy2_x1
#define driver2LeftStickY joystick.joy2_y1
#define driver2RightStickX joystick.joy2_x2
#define driver2RightStickY joystick.joy2_y2

#define driver1BtnA joy1Btn(2)
#define driver1BtnB joy1Btn(3)
#define driver1BtnX joy1Btn(1)
#define driver1BtnY joy1Btn(4)
#define driver1BtnL1 joy1Btn(5)
#define driver1BtnR1 joy1Btn(6)
#define driver1BtnL2 joy1Btn(7)
#define driver1BtnR2 joy1Btn(8)

#define driver2BtnA joy2Btn(2)
#define driver2BtnB joy2Btn(3)
#define driver2BtnX joy2Btn(1)
#define driver2BtnY joy2Btn(4)
#define driver2BtnL1 joy2Btn(5)
#define driver2BtnR1 joy2Btn(6)
#define driver2BtnL2 joy2Btn(7)
#define driver2BtnR2 joy2Btn(8)


int joystickToMotor(int joystickValue)
{

	int motorValue;
	const int minimumValue = 4;
	const int joystickZero = 7;
	if (abs(joystickValue) < joystickZero)
	{
		motorValue = 0;
	}
	else
	{
		const int motorMax = 100;
		int backwards = joystickValue < 0 ? -1 : 1;
		motorValue = (pow(1.05, abs(joystickValue)) / pow(1.05, 127)
			* (motorMax - minimumValue) + minimumValue) * backwards;
	}
	return motorValue;

}

int motorModifiers(int motorValue)
{

	if (driver1BtnR2 || driver2BtnR2)
	{
		motorValue /= 2;
	}

	return motorValue;

}

int fullMotorValue(int joystickValue)
{

	return motorModifiers(joystickToMotor(joystickValue));

}


task main()
{

	int movingLiftTo = -1;

	zeroEncoders();

	waitForStart();

	while (true)
	{

		getJoystickSettings(joystick);

		bool stopAtBottom = true;

		if (driver2BtnL1)
		{
			stopAtBottom = false;
		}

		if (driver2BtnL2)
		{
			zeroEncoders();
		}

		motor[liftLeft] = fullMotorValue(driver2LeftStickY);
		motor[liftRight] = fullMotorValue(driver2RightStickY);

		motor[scoop] = fullMotorValue(driver2RightStickY);

		if (driver1BtnR1 || driver2BtnR1)
		{
			motor[left] = 0;
			motor[right] = 0;
			setLift(0);
			motor[scoop] = 0;
			break;
		}

	}

	return;

}
