#pragma config(Sensor, S1, HTIRS, sensorI2CCustom)
#pragma config(Motor, motorA, right, tmotorNXT, PIDControl, encoder)
#pragma config(Motor, motorB, left, tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard !!*//

//#include "library.c"
#include "C:\Program Files (x86)\Robomatter Inc\ROBOTC Development Environment 4.X\Sample Programs\NXT\3rdPartyDriverLibrary\include\hitechnic-irseeker-v2.h"

// Global variables
int ir[8];

bool hasArrived()
{
	const int arrivedThreshold = 110;
	for (int i = 1; i <= 5; i++)
	{
		if (ir[i] > arrivedThreshold) return true;
	}
	return false;
}

task main()
{

	const int maxSpeed = 60;

	bool wentForwardAlready = false;

	int lastLeft = 1;

	motor[left] = maxSpeed;
	motor[right] = maxSpeed;
	wait1Msec(1500);
	motor[left] = 0;
	motor[right] = 0;

	while(true)
	{

		if (!hasArrived())
		{

			HTIRS2readAllACStrength(HTIRS, ir[1], ir[2], ir[3], ir[4], ir[5]);

			int direction = HTIRS2readACDir(HTIRS);

			// These variables are used only once, because RobotC can't hang
			if (direction == 0)
			{
				if (!wentForwardAlready)
				{
					motor[left] = maxSpeed;
					motor[right] = maxSpeed;
					wait1Msec(1000);
					wentForwardAlready = true;
				}
				else
				{
					motor[left] = lastLeft * maxSpeed;
					int robotCSucks = lastLeft * maxSpeed;
					motor[right] = -1 * robotCSucks;
				}
			}
			else
			{
				wentForwardAlready = false;

				if (direction < 5)
				{
					motor[left] = maxSpeed * -1;
					motor[right] = maxSpeed * 1;
					lastLeft = -1;
				}
				else if (direction > 5)
				{
					motor[left] = maxSpeed * 1;
					motor[right] = maxSpeed * -1;
					lastLeft = 1;
				}
				else if (direction == 5)
				{
					motor[left] = maxSpeed;
					motor[right] = maxSpeed;
					clearTimer(T1);
					while (!hasArrived() && time1[T1] < 1250)	{}
				}
			}

			eraseDisplay();
			displayTextLine(0,"HT IR Seeker");
			displayTextLine(2, "dir: %3d", direction);
			displayTextLine(3, "ir1: %3d", ir[1]);
			displayTextLine(4, "ir2: %3d", ir[2]);
			displayTextLine(5, "ir3: %3d", ir[3]);
			displayTextLine(6, "lol: %3d", motor[left]);
			displayTextLine(7, "ror: %3d", motor[right]);

		}

		if (hasArrived())
		{
			motor[left] = 0;
			motor[right] = 0;
			eraseDisplay();
			displayTextLine(3, "YOU HAVE ARRIVED");
			displayTextLine(4, "AT YOUR");
			displayTextLine(5, "DESTINATION");
			wait1Msec(100);
		}

	}

}
